export const generos = {
  "A": "violet",
  "telejornalismo": "blue",
  "reality": "darkPurple",
  "miniseries": "darkBlue",
  "educacao": "green",
  "infantil": "pink",
  "entrevistas": "yellow",
  "documentarios": "brown",
  "filmes": "red",
  "esportes": "darkGreen",
  "telenovelas": "purple",
  "religiao": "orange",
  "musical": "skyblue",
};